#!/usr/bin/env groovy

/*
 * This script takes the following parameters:
 *
 * Repos and branches
 *  - TEST_BRANCH
 *
 * Build options
 *  - DOCKER_IMAGE_16_04_ACTION
 *  - DOCKER_IMAGE_18_04_ACTION
 *  - DOCKER_IMAGE_20_04_ACTION
 *
 * Environment variables:
 *  - GIT_CREDENTIALS_ID
 *
 */

/* main job */
library identifier: 'mbedtls-test@master', retriever: legacySCM(scm)
dockerfile_builder.run_job()
